### ISSUE TITLE
[Incorrect Content] typo (1 palavra)

### ISSUE THREAD

**Issue by PedromcaMartins** [leic-pt/resumos-leic#810]
### Qual a página que tem o conteúdo incorreto?

https://resumos.leic.pt/pe/variaveis-aleatorias#vari%C3%A1veis-aleat%C3%B3rias-discretas

### O que está incorreto e como ficaria correto?

![image](https://user-images.githubusercontent.com/95452003/176773955-ceb1af5d-4506-471f-91c6-811a5cd07e1c.png)
Onde está marcado a palavra contínuas devi ser discretas

**Comment by randomicecube** [comment]
Fixed in #814
