### ISSUE TITLE
[IAED] Adicionar disclaimer na remoção de elementos em HashTables com Linear Probing

### ISSUE THREAD

**Issue by vugonz** [leic-pt/resumos-leic#826]
https://resumos.leic.pt/iaed/hash-tables#resolução-via-procura-linear-linear-probing
Na parte da remoção de um elemento acho que era boa ideia adicionar uns bullet points a dizer por exemplo:
- Encontrar elemento
- Remover elemento
- Reinserir todos os elementos seguintes até encontrar uma posição vazia

O algoritmo que o Gaspar fez está certo e até é mais eficiente, mas eu estava a rever e confundi-me um bocado, acho que era bom resalvar que o que é dado nas aulas é simplesmente reinserir todos os elementos após o removido até encontrar uma posição vazia e que uma optimização / dirty hack disso é a forma como está lá explicado. 
Please double check my info bcz I'm a bit dumb 
@randomicecube

**Comment by vugonz** [comment]
**Update:**
Estava a fazer um ex de exame e acho que a maneira explicada nos resumos aqui não funciona
Basicamente, ao remover o 27, encontramos o 6 que tem o mesmo hash, colocamos então o 6 no índice 0, porém, o 16 não vai mudar pois o seu índice está certo, isto é, não é preciso ser "chegado para trás"
![hashtable](https://user-images.githubusercontent.com/82618983/178792234-45f45a5b-bd36-404a-b22e-7ca283541f48.png)

Sorry pelo spam

**Comment by randomicecube** [comment]
@vugonz vejo disto assim que puder

**Comment by vugonz** [comment]
Ill make a PR addressing it
