### ISSUE TITLE
[Incorrect Content] Google drive links not working

### ISSUE THREAD

**Issue by guilhas07** [leic-pt/resumos-leic#853]
### Qual a página que tem o conteúdo incorreto?

https://resumos.leic.pt/fis-ii/exercicios/fichas-2021-2022

### O que está incorreto e como ficaria correto?

 Incorrect Links:
 * [Série 1: Efeito Fotoelétrico](https://drive.google.com/file/d/18uyiSQ4ZzDkI_m1D4Gog_Lp5VDQFzYh1/view?usp=sharing)
    * [Resoluções](https://drive.google.com/file/d/1q1bMUXlSDQXx8cjGc448IfJoeRokuR--/view?usp=sharing)
 * [Livro de Exercícios](https://drive.google.com/file/d/1XeUu3FnVETuXMWVm52cDi61H4Uv9KzaA/view?usp=sharing)
 * Módulo 2: Eletrostática
    * [Resoluções](https://drive.google.com/file/d/1suUgtzi40hN7doYIl18lum2_Mw-X0sdX/view?usp=sharing)
    * [Resoluções - Pedro Chaparro](https://drive.google.com/file/d/1UxmoDqKaKnyktkh35kQs81IbFnKblZlZ/view?usp=sharing)

![image](https://user-images.githubusercontent.com/48023091/195078369-ffc0e898-4169-400e-80f8-ebf7faedf496.png)

**Comment by diogotcorreia** [comment]
Refer to #558 

Some of those files were deleted for that reason, but they were never removed from the site.
I'll removed them now, thanks for the heads up.
