### ISSUE TITLE
Automatic contributors list

### ISSUE THREAD

**Issue by diogotcorreia** [leic-pt/resumos-leic#866]
We have a lot of (new) contributors, or existing contributors that start contributing to other courses.

It gets difficult to keep the contributors list up-to-date.
I'd be great if we could generate the contributors list from the GitHub API, crossing commits and PRs with their labels (not sure how this would go for older PRs that don't have labels).

A file that can manually add contributors would also be great to add non-code contributors or co-authors.

Cache would be important to avoid hitting the GitHub API rate limit (ideally we'd have a Personal Access Token in production to increase the rate limit).

**Comment by Lourencom** [comment]
I created a github workflow that automatically runs on every push.
The github actions-bot runs after the commit, fetches the author and course, and if necessary creates a new commit to update the contributors list.
If no course specified or not necessary, it just doesn't do anything.

But for this to work we need to enable write permissions for github actions bot:
![image](https://github.com/leic-pt/resumos-leic/assets/80357060/5e43930d-988c-490c-82cc-fddf8930bbaa)

I will create a PR, feel free to change anything if you want.
