### ISSUE TITLE
[TC] [Incorrect Content] Prova Turing Machines Unidirecionais equivalentes a Bidirecionais

### ISSUE THREAD

**Issue by andIsome** [leic-pt/resumos-leic#955]
### Qual a página que tem o conteúdo incorreto?

https://resumos.leic.pt/tc/maquinas-de-turing/#m%C3%A1quinas-bidirecionais:~:text=de%20Turing%20unidirecional.-,Prova,-M%C3%A1quina%20multifita

### O que está incorreto e como ficaria correto?

No seguinte texto fala da prova de Turing machines unidirecionais serem equivalentes a bidirecionais (no dropdown prova):

Desta forma, criamos um espaço na primeira posição onde podemos colocar o símbolo determinado pela computação da fita bidirecional. Uma forma de saber quando precisamos de um espaço à esquerda é, 
**_antes da computação, movermos o input um espaço para a esquerda_**.
 Assim, sempre que lermos um espaço em branco depois de fazermos um movimento para a esquerda, quer dizer que precisamos de mais um espaço à esquerda.
 
 devia ser: movermos o input um espaço para a _**direita**_

**Comment by diogotcorreia** [comment]
@Calhau18

**Comment by Calhau18** [comment]
:+1: isto é uma gafe.
